### PR TITLE
docs: add 'supported platforms' notes to README

### LINKED ISSUE #50: Update README to clarify supported OS
The README currently offers some notes for supporting OSX, but since we won't be able to support any platform folks may want to run this on, we should explicitly state what we do support (aka: Linux).

### PR DESCRIPTION
**Pull request by rpappalax**
r? @bbangert 

Closes #50

### CODE REVIEW

**Comment by bbangert** [comment]
Looks good, though the commit message should be in the format the CONTRIBUTING documents.

**Comment by rpappalax** [comment]
thanks @bbangert, i'll pay more attention to that next time.  hopefully, ok now

**Comment by bbangert** [comment]
I think this needs to be rebased aginst, or it will include a duplicate commit of my multiple scenario fix.

**Comment by bbangert** [comment]
r+

**Pull request merged**
