### PR TITLE
fix: use hyphenated uuid's for latest autopush normalization

### LINKED ISSUE #34: Use dashes in uaid/chids per UUID normalization
autopush now normalizes chids/uaids to include dahes, only channels made with them should be submitted.

### PR DESCRIPTION
**Pull request by bbangert**
Closes #34

@jrconlin r?

### CODE REVIEW

**Comment by jrconlin** [comment]
fixup https://github.com/mozilla-services/ap-loadtester/blob/4ceae8ddb96bddd562178cb4a1cea47808b1b436/SCENARIOS.md#L158 and like?

**Comment by bbangert** [comment]
huh?

**Comment by jrconlin** [comment]
The UUIDs specified in that document are not '-' delimited. It's a minor nit.

**Comment by jrconlin** [comment]
r+

**Pull request merged**
